# Generated by Django 4.1.3 on 2022-11-12 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_reply_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='text',
            field=models.TextField(max_length=400, verbose_name='Reply'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='app.theme', verbose_name='Theme'),
        ),
    ]
